name: build-linux
# <arch>-<vendor>-<os>-<env>

on:
  workflow_dispatch:
  push:
    # tags:
    #   - "v*"
  # workflow_call:
  # schedule:
  #   - cron: "0 2 * * *" # run at 2 AM UTC

jobs:
  build-linux:
    runs-on: ubuntu-22.04

    strategy:
      # max-parallel: 1
      fail-fast: false
      matrix:
        include: 
          - target: wasi32
            artifact: libbarretenberg_wasm
          - target: aarch64-multiplatform
            artifact: libbarretenberg

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - uses: actions/cache@v3
      #   with:
      #     path: |
      #       ~/.cargo/bin/
      #       ~/.cargo/registry/index/
      #       ~/.cargo/registry/cache/
      #       ~/.cargo/git/db/
      #       target/
      #     key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-22.11

      - uses: cachix/cachix-action@v12
        with:
          name: nargo-cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build ${{ matrix.artifact }} for ${{ matrix.target }}
        run: |
          nix build .#pkgsCross.${{ matrix.target }}.${{ matrix.artifact }}

      - name: Upload ${{ matrix.artifact }}-${{ matrix.target }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact }}-${{ matrix.target }}
          path: ./result
          retention-days: 3
