name: build-linux

on:
  workflow_dispatch:
  push:

jobs:
  build-linux:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        target: [
            # llvm11, llvm12, llvm13, 
            llvm14, wasm32,
            cross-aarch64-linux,
          ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v19
        with:
          nix_path: nixpkgs=channel:nixos-22.11
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build barretenberg on ${{ matrix.target }}
        run: |
          nix build -L .#${{ matrix.target }}

      - name: Prepare artifacts
        run: |
          mkdir artifacts
          cp -a ./result/. artifacts

      - name: Upload ${{ matrix.artifact }}-${{ matrix.target }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: ./artifacts/
          retention-days: 3

      - name: Package artifacts
        run: |
          7z a -ttar -so -an ./artifacts/* | 7z a -si ./libbarretenberg-${{ matrix.target }}.tar.gz

      - name: Upload binaries
        uses: svenstaro/upload-release-action@v2
        # if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        with:
          file: ./libbarretenberg-${{ matrix.target }}.tar.gz
          asset_name: libbarretenberg-${{ matrix.target }}.tar.gz
          overwrite: true
          tag: ${{ github.ref }}

  bb_wrapper:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v19
        with:
          nix_path: nixpkgs=channel:nixos-22.11
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build barretenberg_wrapper
        working-directory: ./barretenberg_wrapper
        # This removes the lockfile as a workaround to relative file paths causing a failure in flakes
        run: |
          rm flake.lock
          nix build -L
          ./result/bin/barretenberg_wrapper

