name: update-repository
# <arch>-<vendor>-<os>-<env>

on:
  workflow_dispatch:
  # workflow_call:
  # schedule:
  #   - cron: "0 2 * * *" # run at 2 AM UTC
  # push:
  #   tags:
  #     - "v*"

jobs:
  update-repository:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-22.11

      - uses: cachix/cachix-action@v12
        with:
          name: nargo-cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build environment and Compile
        run: |
          nix build .#pkgsCross.aarch64-multiplatform.libbarretenberg
